services:
  api: &main_app
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: douban_api:${DOUBAN_API_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      DOUBAN_API_HOST: 0.0.0.0


